project:
  type: website
  output-dir: docs

website:
  title: "The Project"
  navbar:
    background: "#FDF0E9"
    left:
      - text: "Home"
        href: index.qmd
        - text: "Gundu"
        href: about.qmd
      - text: "Lil us"
        href: beginning.qmd
      - text: "Our Story"
        href: story.qmd
      - text: "Present Day"
        href: present.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



